export const COUNTRIES = [
	'Afghanistan',
	'Aland Islands',
	'Albania',
	'Algeria',
	'Andorra',
	'Angola',
	'Anguilla',
	'Antigua And Barbuda',
	'Argentina',
	'Armenia',
	'Aruba',
	'Australia',
	'Austria',
	'Azerbaijan',
	'Bahamas',
	'Bahrain',
	'Bangladesh',
	'Barbados',
	'Belarus',
	'Belgium',
	'Belize, ',
	'Benin',
	'Bermuda',
	'Bhutan',
	'Bolivia',
	'Bosnia And Herzegovina',
	'Botswana',
	'Bouvet Island',
	'Brazil',
	'British Indian Ocean Territory',
	'Brunei',
	'Bulgaria',
	'Burkina Faso',
	'Burundi',
	'Cambodia',
	'Canada, ',
	'Cape Verde',
	'Cayman Islands',
	'Central African Republic, ',
	'Chad',
	'Chile',
	'China',
	'Christmas Island',
	'Cocos (Keeling) Islands',
	'Colombia',
	'Comoros, ',
	'Congo ',
	'Congo, The Democratic Republic Of The ',
	'Cook Islands ',
	'Costa Rica',
	'Croatia',
	'Cuba',
	'Curaçao',
	'Cyprus, ',
	'Czech Republic ',
	"Côte d'Ivoir'e",
	'Denmark',
	'Djibouti',
	'Dominica',
	'Dominican Republic',
	'Ecuador, ',
	'Egypt ',
	'El Salvador',
	'Equatorial Guinea',
	'Eritrea',
	'Estonia',
	'Ethiopia',
	'Falkland Islands (Malvinas), ',
	'Faroe Islands ',
	'Fiji',
	'Finland',
	'France',
	'French Guiana',
	'French Polynesia',
	'French Southern Territories, ',
	'Gabon',
	'Gambia',
	'Georgia',
	'Germany, ',
	'Ghana',
	'Gibraltar',
	'Greece',
	'Greenland',
	'Grenada',
	'Guadeloupe',
	'Guatemala',
	'Guernsey',
	'Guinea',
	'Guinea Bissau',
	'Guyana, ',
	'Haiti ',
	'Heard Island And Mcdonald Islands ',
	'Holy See (Vatican City State)',
	'Honduras',
	'Hong Kong',
	'Hungary',
	'Iceland, ',
	'India',
	'Indonesia',
	'Iran, Islamic Republic Of ',
	'Iraq',
	'Ireland',
	'Isle Of Man',
	'Israel',
	'Italy',
	'Jamaica',
	'Japan',
	'Jersey',
	'Jordan',
	'Kazakhstan, ',
	'Kenya',
	'Kiribati',
	"Korea, Democratic People's Republic",
	'Kosovo',
	'Kuwait',
	'Kyrgyzstan, ',
	"Lao People's Democratic Republic",
	'Latvia',
	'Lebanon',
	'Lesotho',
	'Liberia',
	'Libyan Arab Jamahiriya',
	'Liechtenstein',
	'Lithuania',
	'Luxembourg, ',
	'Macao',
	'Macedonia, Republic Of',
	'Madagascar',
	'Malawi',
	'Malaysia',
	'Maldives, ',
	'Mali',
	'Malta',
	'Martinique',
	'Mauritania',
	'Mauritius',
	'Mayotte',
	'Mexico',
	'Moldova, Republic of',
	'Monaco',
	'Mongolia',
	'Montenegro',
	'Montserrat',
	'Morocco',
	'Mozambique',
	'Myanmar',
	'Namibia, ',
	'Nauru ',
	'Nepal',
	'Netherlands',
	'Netherlands Antilles, ',
	'New Caledonia ',
	'New Zealand',
	'Nicaragua',
	'Niger',
	'Nigeria',
	'Niue',
	'Norfolk Island',
	'Norway, ',
	'Oman',
	'Pakistan',
	'Palestinian Territory, Occupied',
	'Panama, ',
	'Papua New Guinea',
	'Paraguay',
	'Peru',
	'Philippines',
	'Pitcairn',
	'Poland',
	'Portugal, ',
	'Qatar',
	'Republic of Cameroon',
	'Reunion',
	'Romania',
	'Russia',
	'Rwanda, ',
	'Saint Barthélemy ',
	'Saint Helena ',
	'Saint Kitts And Nevis ',
	'Saint Lucia ',
	'Saint Martin ',
	'Saint Pierre And Miquelon ',
	'Samoa ',
	'San Marino ',
	'Sao Tome And Principe ',
	'Saudi Arabia',
	'Senegal',
	'Serbia',
	'Seychelles',
	'Sierra Leone',
	'Singapore, ',
	'Sint Maarten',
	'Slovakia',
	'Slovenia',
	'Solomon Islands',
	'Somalia, ',
	'South Africa ',
	'South Georgia And The South Sandwich Islands ',
	'South Korea ',
	'Spain ',
	'Sri Lanka ',
	'St. Vincent ',
	'Sudan',
	'Suriname',
	'Svalbard And Jan Mayen',
	'Swaziland',
	'Sweden',
	'Switzerland, ',
	'Syria',
	'Taiwan',
	'Tajikistan',
	'Tanzania, United Republic Of',
	'Thailand, ',
	'Timor Leste ',
	'Togo',
	'Tokelau, ',
	'Tonga',
	'Trinidad and Tobago',
	'Tunisia',
	'Turkey',
	'Turkmenistan, ',
	'Turks and Caicos Islands',
	'Tuvalu',
	'Uganda',
	'Ukraine',
	'United Arab Emirates',
	'United Kingdom',
	'United States',
	'United States Minor Outlying Islands',
	'Uruguay',
	'Uzbekistan',
	'Vanuatu',
	'Venezuela',
	'Vietnam',
	'Virgin Islands, British',
	'Wallis And Futuna',
	'Western Sahara',
	'Yemen',
	'Zambia',
	'Zimbabwe',
];
